### ISSUE TITLE
Socket.gaierror on GetSatelliteIR

### ISSUE THREAD

**Issue by surajshah2** [Unidata/python-awips#11]
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

Followed all the install steps, dowloaded the repo, called
`python setup.py build`
`python setup.py install`

Used Sublime to create Python file containing this code

```python
#!/awips2/python/bin/python
from awips.dataaccess import DataAccessLayer
import numpy as np

request = DataAccessLayer.newDataRequest()
request.setDatatype("satellite")
request.setLocationNames("East CONUS")
request.setParameters("Imager 6.7-6.5 micron IR (WV)")

t = DataAccessLayer.getAvailableTimes(request)
print t[-1].getRefTime()

response = DataAccessLayer.getGridData(request, times=[t[-1]])
print response
data = response[0]

print 'Units are in', data.getUnit()
lon,lat = data.getLatLonCoords()

print 'Parameter we requested is',data.getParameter()
print data.getRawData()
```

Full Log
```
Traceback (most recent call last):
  File "weatherInfo.py", line 10, in <module>
    t = DataAccessLayer.getAvailableTimes(request)
  File "/Users/newuser/Downloads/python-awips-master/awips/dataaccess/DataAccessLayer.py", line 71, in getAvailableTimes
    return router.getAvailableTimes(request, refTimeOnly)
  File "/Users/newuser/Downloads/python-awips-master/awips/dataaccess/ThriftClientRouter.py", line 57, in getAvailableTimes
    response = self._client.sendRequest(timesRequest)
  File "/Users/newuser/Downloads/python-awips-master/awips/ThriftClient.py", line 56, in sendRequest
    self.__httpConn.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by mjames-upc** [comment]
To begin you need to specify a remote host to request from:

`DataAccessLayer.changeEDEXHost("edex-cloud.unidata.ucar.edu")`
