### ISSUE TITLE
unidata-workshop pip python-awips install failure

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/python-awips#15]
referenced at https://github.com/Unidata/unidata-python-workshop/issues/348
for the file `environment.yml`

```
 name: unidata-workshop
 channels:
   - conda-forge
 dependencies:
   - python=3.6
   - numpy
   - nomkl
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - owslib
   - metpy
   - pint
   - shapely
   - siphon
   - xarray
   - pip
   - ffmpeg
   - pytest
   - pip:
     - python-awips
```

```
conda env update -f environment.yml 

Solving environment: done

Downloading and Extracting Packages
pip-18.0             | 1.8 MB    | ################################################################################################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting python-awips (from -r /Users/mjames/unidata-python-workshop/condaenv.pn_95g9y.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/3a/05/7d0c53f27af89b4dab569328acd5c6740cccd1f662edce1201fb4fc20bad/python-awips-18.1.2.tar.gz (166kB)
    100% |████████████████████████████████| 174kB 2.5MB/s 
Requirement already satisfied: numpy in /Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages (from python-awips->-r /Users/mjames/unidata-python-workshop/condaenv.pn_95g9y.requirements.txt (line 1)) (1.15.2)
Requirement already satisfied: six in /Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages (from python-awips->-r /Users/mjames/unidata-python-workshop/condaenv.pn_95g9y.requirements.txt (line 1)) (1.11.0)
Building wheels for collected packages: python-awips
  Running setup.py bdist_wheel for python-awips ... done
  Stored in directory: /Users/mjames/Library/Caches/pip/wheels/ad/15/e9/67c4cdb77e0f896d713f87e020d3dc98c21a8ae315ce7c2d8a
Successfully built python-awips
Exception:
Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in _dep_map
    return self.__dep_map
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2949, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; extra '"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 330, in run
    self._warn_about_conflicts(to_install)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 456, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 98, in check_install_conflicts
    package_set = create_package_set_from_installed()
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2871, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2881, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2942, in parse_requirements
    yield Requirement(line)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2951, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"

CondaValueError: pip returned an error

```

previous message

``` 
conda env update -f environment.yml 

Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting python-awips (from -r /Users/mjames/unidata-python-workshop/condaenv.zn2xq7f0.requirements.txt (line 1))
Requirement already satisfied: numpy in /Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages (from python-awips->-r /Users/mjames/unidata-python-workshop/condaenv.zn2xq7f0.requirements.txt (line 1)) (1.15.2)
Requirement already satisfied: six in /Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages (from python-awips->-r /Users/mjames/unidata-python-workshop/condaenv.zn2xq7f0.requirements.txt (line 1)) (1.11.0)
Exception:
Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in _dep_map
    return self.__dep_map
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2949, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; extra '"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 330, in run
    self._warn_about_conflicts(to_install)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 456, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 98, in check_install_conflicts
    package_set = create_package_set_from_installed()
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2871, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2881, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2942, in parse_requirements
    yield Requirement(line)
  File "/Users/mjames/miniconda3/envs/unidata-workshop/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2951, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"

CondaValueError: pip returned an error


```

**Comment by mjames-upc** [comment]
```
conda list
# packages in environment at /Users/mjames/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0  
beautifulsoup4            4.6.3                    py37_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.8.24                py37_1  
cffi                      1.11.5           py37h6174b99_1  
chardet                   3.0.4                    py37_1  
click                     6.7                      py37_0  
conda                     4.5.11                   py37_0  
conda-build               3.15.1                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.0                    py37_0  
cryptography              2.3.1            py37hdbc3d79_0  
filelock                  3.0.8                    py37_0  
future                    0.16.0                   py37_0  
glob2                     0.6                      py37_0  
idna                      2.7                      py37_0  
jinja2                    2.10                     py37_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
markupsafe                1.0              py37h1de35cc_1  
ncurses                   6.1                  h0a44026_0  
openssl                   1.0.2p               h1de35cc_0  
pip                       10.0.1                   py37_0  
pkginfo                   1.4.2                    py37_1  
psutil                    5.4.7            py37h1de35cc_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.18                     py37_1  
pyopenssl                 18.0.0                   py37_0  
pysocks                   1.6.8                    py37_0  
python                    3.7.0                hc167b69_0  
python.app                2                        py37_8  
pytz                      2018.5                   py37_0  
pyyaml                    3.13             py37h1de35cc_0  
readline                  7.0                  h1de35cc_5  
requests                  2.19.1                   py37_0  
ruamel_yaml               0.15.46          py37h1de35cc_0  
setuptools                40.2.0                   py37_0  
six                       1.11.0                   py37_1  
sqlite                    3.24.0               ha441bb4_0  
testpath                  0.3.1                    py37_0  
tk                        8.6.8                ha441bb4_0  
tqdm                      4.26.0           py37h28b3542_0  
urllib3                   1.23                     py37_0  
wheel                     0.31.1                   py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zlib                      1.2.11               hf3cbc9b_2  

```

**Comment by mjames-upc** [comment]
https://github.com/conda-forge/testpath-feedstock/issues/7
