### ISSUE TITLE
ERROR: testGetAvailableLocations (awips.test.dafTests.testClimate.ClimateTestCase)

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/python-awips#19]
```
======================================================================
ERROR: testGetAvailableLocations (awips.test.dafTests.testClimate.ClimateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/scrutinizer/build/awips/test/dafTests/testClimate.py", line 49, in testGetAvailableLocations
    self.runLocationsTest(req)
  File "/home/scrutinizer/build/awips/test/dafTests/baseDafTestCase.py", line 123, in runLocationsTest
    locs = DAL.getAvailableLocationNames(req)
  File "/home/scrutinizer/build/awips/dataaccess/DataAccessLayer.py", line 208, in getAvailableLocationNames
    return router.getAvailableLocationNames(request)
  File "/home/scrutinizer/build/awips/dataaccess/ThriftClientRouter.py", line 167, in getAvailableLocationNames
    response = self._client.sendRequest(locNamesRequest)
  File "/home/scrutinizer/build/awips/ThriftClient.py", line 68, in sendRequest
    raise ThriftRequestException(forceError)
awips.ThriftClient.ThriftRequestException: b'com.raytheon.uf.common.dataaccess.exception.DataRetrievalException' exception thrown: b'Error retrieving climate data (failed query="select column_name from information_schema.columns where column_name in (\'station_code\', \'station_id\', \'inform_id\', \'icao_loc_id\') and table_name = \'cli_asos_monthly\';")'
	at com.raytheon.uf.common.dataaccess.util.DatabaseQueryUtil.executeDatabaseQuery(DatabaseQueryUtil.java:129)
	at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.executeQuery(AbstractGeometryDatabaseFactory.java:238)
	at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.executeGetColumnNames(AbstractGeometryDatabaseFactory.java:628)
	at com.raytheon.uf.common.dataplugin.climate.ClimateGeometryFactory.getLocationColumnName(ClimateGeometryFactory.java:173)
	at com.raytheon.uf.common.dataplugin.climate.ClimateGeometryFactory.assembleGetAvailableLocationNames(ClimateGeometryFactory.java:189)
	at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.getAvailableLocationNames(AbstractGeometryDatabaseFactory.java:246)
	at com.raytheon.uf.common.dataaccess.DataAccessLayer.getAvailableLocationNames(DataAccessLayer.java:211)
	at com.raytheon.uf.edex.dataaccess.handler.GetAvailableLocationNamesHandler.handleRequest(GetAvailableLocationNamesHandler.java:57)
	at com.raytheon.uf.edex.dataaccess.handler.GetAvailableLocationNamesHandler.handleRequest(GetAvailableLocationNamesHandler.java:1)
	at com.raytheon.uf.edex.requestsrv.RequestServiceExecutor.execute(RequestServiceExecutor.java:155)
	at com.raytheon.uf.edex.requestsrv.serialization.SerializingStreamExecutor.execute(SerializingStreamExecutor.java:107)
	at com.raytheon.uf.edex.requestsrv.serialization.ByteLimitingStreamExecutor.execute(ByteLimitingStreamExecutor.java:76)
	at com.raytheon.uf.edex.requestsrv.http.HttpRequestServiceExecutor.execute(HttpRequestServiceExecutor.java:102)
	at sun.reflect.GeneratedMethodAccessor137.invoke()
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:458)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:289)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:262)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:178)
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:41)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:116)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.component.jetty.CamelContinuationServlet.doService(CamelContinuationServlet.java:191)
	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: b'java.lang.NullPointerException' exception thrown: 
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.raytheon.uf.edex.database.dao.CoreDao.executeSQLQuery(CoreDao.java:894)
	at com.raytheon.uf.edex.database.dao.CoreDao.executeSQLQuery(CoreDao.java:875)
	at com.raytheon.uf.edex.database.dao.CoreDao.executeMappedSQLQuery(CoreDao.java:953)
	at com.raytheon.uf.edex.database.QlServerRequestHandler.handleRequest(QlServerRequestHandler.java:74)
	at com.raytheon.uf.edex.database.QlServerRequestHandler.handleRequest(QlServerRequestHandler.java:1)
	at com.raytheon.uf.edex.requestsrv.RequestServiceExecutor.execute(RequestServiceExecutor.java:155)
	at com.raytheon.uf.edex.requestsrv.router.ServerRequestRouter.route(ServerRequestRouter.java:58)
	at com.raytheon.uf.common.serialization.comm.RequestRouter.route(RequestRouter.java:130)
	at com.raytheon.uf.common.serialization.comm.RequestRouter.route(RequestRouter.java:107)
	at com.raytheon.uf.common.dataaccess.util.DatabaseQueryUtil.executeDatabaseQuery(DatabaseQueryUtil.java:127)
	at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.executeQuery(AbstractGeometryDatabaseFactory.java:238)
	at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.executeGetColumnNames(AbstractGeometryDatabaseFactory.java:628)
	at com.raytheon.uf.common.dataplugin.climate.ClimateGeometryFactory.getLocationColumnName(ClimateGeometryFactory.java:173)
	at com.raytheon.uf.common.dataplugin.climate.ClimateGeometryFactory.assembleGetAvailableLocationNames(ClimateGeometryFactory.java:189)
	at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.getAvailableLocationNames(AbstractGeometryDatabaseFactory.java:246)
	at com.raytheon.uf.common.dataaccess.DataAccessLayer.getAvailableLocationNames(DataAccessLayer.java:211)
	at com.raytheon.uf.edex.dataaccess.handler.GetAvailableLocationNamesHandler.handleRequest(GetAvailableLocationNamesHandler.java:57)
	at com.raytheon.uf.edex.dataaccess.handler.GetAvailableLocationNamesHandler.handleRequest(GetAvailableLocationNamesHandler.java:1)
	at com.raytheon.uf.edex.requestsrv.RequestServiceExecutor.execute(RequestServiceExecutor.java:155)
	at com.raytheon.uf.edex.requestsrv.serialization.SerializingStreamExecutor.execute(SerializingStreamExecutor.java:107)
	at com.raytheon.uf.edex.requestsrv.serialization.ByteLimitingStreamExecutor.execute(ByteLimitingStreamExecutor.java:76)
	at com.raytheon.uf.edex.requestsrv.http.HttpRequestServiceExecutor.execute(HttpRequestServiceExecutor.java:102)
	at sun.reflect.GeneratedMethodAccessor137.invoke()
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:458)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:289)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:262)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:178)
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:41)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:116)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.component.jetty.CamelContinuationServlet.doService(CamelContinuationServlet.java:191)
	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by mjames-upc** [comment]
query is 
```
"select column_name from information_schema.columns where column_name in 
(\'station_code\', \'station_id\', \'inform_id\', \'icao_loc_id\') and table_name = \'cli_asos_monthly\';"
```

**Comment by mjames-upc** [comment]
```
climate=> \d cli_asos_monthly;
            Table "public.cli_asos_monthly"
       Column       |         Type          | Modifiers 
--------------------+-----------------------+-----------
 station_code       | character varying(9)  | not null
 year               | smallint              | 
 month              | smallint              | not null
 maxtemp_mon        | smallint              | 
 maxtemp_day1       | smallint              | 
 maxtemp_day2       | smallint              | 
 maxtemp_day3       | smallint              | 
 mintemp_mon        | smallint              | 
 mintemp_day1       | smallint              | 
 mintemp_day2       | smallint              | 
 mintemp_day3       | smallint              | 
 avg_daily_max      | real                  | 
 avg_daily_min      | real                  | 
 avg_mon_temp       | real                  | 
 days_maxt_blo_fzg  | smallint              | 
 days_maxt_hot      | smallint              | 
 days_mint_blo_fzg  | smallint              | 
 days_mint_blo_0f   | smallint              | 
 heating            | smallint              | 
 cooling            | smallint              | 
 mean_stn_press     | real                  | 
 mean_sea_press     | real                  | 
 max_sea_press      | real                  | 
 max_slp_date       | character varying(8)  | 
 max_slp_occur      | character varying(1)  | 
 min_sea_press      | real                  | 
 min_slp_date       | character varying(8)  | 
 min_slp_occur      | character varying(1)  | 
 month_precip       | real                  | 
 days_hundreth      | smallint              | 
 days_tenth         | smallint              | 
 days_half          | smallint              | 
 days_inch          | smallint              | 
 max_24h_pcp        | real                  | 
 max_24h_pcp_day1   | smallint              | 
 max_24h_pcp_day2   | smallint              | 
 shrtdurpcp5        | real                  | 
 shrtdurpcp10       | real                  | 
 shrtdurpcp15       | real                  | 
 shrtdurpcp20       | real                  | 
 shrtdurpcp30       | real                  | 
 shrtdurpcp45       | real                  | 
 shrtdurpcp60       | real                  | 
 shrtdurpcp80       | real                  | 
 shrtdurpcp100      | real                  | 
 shrtdurpcp120      | real                  | 
 shrtdurpcp150      | real                  | 
 shrtdurpcp180      | real                  | 
 shrtdurpcp_date5   | character varying(8)  | 
 shrtdurpcp_date10  | character varying(8)  | 
 shrtdurpcp_date15  | character varying(8)  | 
 shrtdurpcp_date20  | character varying(8)  | 
 shrtdurpcp_date30  | character varying(8)  | 
 shrtdurpcp_date45  | character varying(8)  | 
 shrtdurpcp_date60  | character varying(8)  | 
 shrtdurpcp_date80  | character varying(8)  | 
 shrtdurpcp_date100 | character varying(8)  | 
 shrtdurpcp_date120 | character varying(8)  | 
 shrtdurpcp_date150 | character varying(8)  | 
 shrtdurpcp_date180 | character varying(8)  | 
 hrs_sun            | real                  | 
 percent_sun        | real                  | 
 max_24h_snow       | real                  | 
 max_24h_snow_date1 | smallint              | 
 max_24h_snow_date2 | smallint              | 
 snowdepth          | smallint              | 
 snowdepth_date     | smallint              | 
 clear_days         | smallint              | 
 pcloud_days        | smallint              | 
 cloud_days         | smallint              | 
 remarks            | character varying(20) | 
Indexes:
    "cli_asos_monthly_pk" PRIMARY KEY, btree (station_code, month)
    "p189_250" UNIQUE, btree (station_code, month)


```

**Comment by mjames-upc** [comment]
```
DefaultDataRequest(
datatype=climate, 
identifiers={'table': 'public.cli_asos_monthly'}, 
parameters=[], levels=[], locationNames=[], envelope=None)
```

**Comment by mjames-upc** [comment]
```
ERROR 2018-10-16 19:38:23,238 3005 [qtp534951830-4227] ThriftSrvRequestLogger: EDEX: ThriftSrvRequestLogger - Error executing request: com.raytheon.uf.common.dataaccess.request.GetAvailableParametersRequest@78441339:
com.raytheon.uf.common.dataaccess.exception.DataRetrievalException: Error retrieving climate data (failed query="select column_name from information_schema.columns where table_schema = 'public' and table_name = 'cli_asos_monthly';")
        at com.raytheon.uf.common.dataaccess.util.DatabaseQueryUtil.executeDatabaseQuery(DatabaseQueryUtil.java:129) ~[com.raytheon.uf.common.dataaccess.jar:na]
        at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.executeQuery(AbstractGeometryDatabaseFactory.java:238) ~[com.raytheon.uf.common.dataaccess.jar:na]
        at com.raytheon.uf.common.dataaccess.impl.AbstractGeometryDatabaseFactory.getAvailableParameters(AbstractGeometryDatabaseFactory.java:259) ~[com.raytheon.uf.common.dataaccess.jar:na]
        at com.raytheon.uf.common.dataaccess.DataAccessLayer.getAvailableParameters(DataAccessLayer.java:254) ~[com.raytheon.uf.common.dataaccess.jar:na]
        at com.raytheon.uf.edex.dataaccess.handler.GetAvailableParametersHandler.handleRequest(GetAvailableParametersHandler.java:49) ~[com.raytheon.uf.edex.dataaccess.jar:na]
        at com.raytheon.uf.edex.dataaccess.handler.GetAvailableParametersHandler.handleRequest(GetAvailableParametersHandler.java:1) ~[com.raytheon.uf.edex.dataaccess.jar:na]
        at com.raytheon.uf.edex.requestsrv.RequestServiceExecutor.execute(RequestServiceExecutor.java:155) ~[com.raytheon.uf.edex.requestsrv.jar:na]
        at com.raytheon.uf.edex.requestsrv.serialization.SerializingStreamExecutor.execute(SerializingStreamExecutor.java:107) ~[com.raytheon.uf.edex.requestsrv.jar:na]
        at com.raytheon.uf.edex.requestsrv.serialization.ByteLimitingStreamExecutor.execute(ByteLimitingStreamExecutor.java:76) [com.raytheon.uf.edex.requestsrv.jar:na]
        at com.raytheon.uf.edex.requestsrv.http.HttpRequestServiceExecutor.execute(HttpRequestServiceExecutor.java:102) [com.raytheon.uf.edex.requestsrv.jar:na]
        at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
...
```

**Comment by mjames-upc** [comment]
in pg_logs:

```
2018-10-16 19:42:34 UTC 0 climate : [local] : ERROR:  syntax error at or near "failed" at character 2
2018-10-16 19:42:34 UTC 0 climate : [local] : STATEMENT:  (failed query="select column_name from information_schema.columns where table_schema = 'public' and table_name = 'cli_asos_monthly';")
 
```
